# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Git status symbols:
# $ â€” stashed changes
# ! â€” modified files
# + â€” staged files
# ? â€” untracked files
# âœ˜ â€” deleted files
# â‡¡ â€” ahead of remote
# â‡£ â€” behind remote
format = """
$git_branch$git_state$git_status$git_metrics
$git_commit${custom.git_commit_message}
$directory
$username$hostname$character
"""

[username]
format = '[$user]($style) '

[hostname]
format = '[$ssh_symbol$hostname]($style) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
only_detached = false
commit_hash_length = 6
tag_symbol = 'ðŸ”– '
format = '[$hash]($style)'

[custom.git_commit_message]
command = 'git log -1 --format=%s'
when = 'git rev-parse --git-dir'
format = ' [$output]($style)'
style = 'yellow'
description = 'Latest git commit message header'

[directory]
truncate_to_repo = true
truncation_length = 7
format = 'ðŸ“‚ [$path]($style)[$read_only]($read_only_style) '
repo_root_format = 'ðŸ“¦ [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
repo_root_style = 'bold cyan'
