# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[git_commit]
only_detached = false
commit_hash_length = 6
tag_symbol = 'ðŸ”– '

[rust]
disabled = true

[nodejs]
disabled = true

[direnv]
disabled = true

[nix_shell]
disabled = true

[directory]
truncate_to_repo = false
